apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  labels:
    {{ toYaml .Values.server.commonLabels }}
  annotations:
    eks.amazonaws.com/role-arn: {{ quote .Values.serviceAccount.irsa_arn }}
