name: Build and Push

on:
  push:
    branches:
      - 'emv/**'
      - main

jobs:
  build:
    name: Build & Push docker image
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      # TODO: investigate how to assume role to follow best practices
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          IMAGE_NAME: '${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY }}'

        run: |
          docker build -t $IMAGE_NAME:$(git rev-parse --short $GITHUB_SHA) -t $IMAGE_NAME:latest .
          docker image push --all-tags $IMAGE_NAME
