name: Deploy via Helm
on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
    inputs:
      imageTag:
        type: string
        description: "Image tag"
        required: true
        default: latest

      namespace:
        type: choice
        description: "Namespace"
        required: true
        default: "default"
        options:
          - main
          - dev


jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE_ARN }}
          mask-aws-account-id: false

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name demo

      - name: Install using Helm
        run: helm install
